### ISSUE TITLE
Missing file `sIntClear.h`

### ISSUE THREAD

**Issue by fabrice102** [ladnir/Ivory-Runtime#1]
I think the file `sIntClear.h` is missing.

**Comment by ladnir** [comment]
yeah, my computer bricked the other day and I pushed a bunch of partial updates before having to reinstall...  :/

I'll roll things back to a working commit.

**Comment by fabrice102** [comment]
Thanks! By the way, the folder `cryptoTools` is not used and is empty.

**Comment by ladnir** [comment]
ok it should work now. Note that I just pushed a big update to libOTe and it appears to not play well with  ivory. So you will need to checkout libOTe @ 8f071c3 and  and cryptoTools @ a755c51

**Comment by ladnir** [comment]
ok, the problem was actually with ivory which is fixed now. You can use the latest of everything.
