### ISSUE TITLE
A build Problem

### ISSUE THREAD

**Issue by taxuexunshang** [ladnir/Ivory-Runtime#7]
I built on top of libOTe v1.6.0 with the following build command
`python3 build.py --boost --relic -D ENABLE_ALL_OT=ON -D ENABLE_CIRCUITS=ON`
But when I run the make command on Ivory-Runtime, I get the following error
<img width="1440" alt="image" src="https://github.com/ladnir/Ivory-Runtime/assets/30920584/b3659bde-9b5b-4989-9b10-4c00c90fdcd1">
Please give us your guidance in your free time, thank you very much!

**Comment by ladnir** [comment]
delete everything and follow the new readme

**Comment by taxuexunshang** [comment]
Thank you very much for your help!!!
